/*  messages.c - Messages generated by libcpak.
    
    Copyright 2013  Francisco Jose Monaco   <monaco.fj@gmail.com>

    This file is part of Libcpak. 

    Libcpak is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Libcpak is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with .  If not, see <http://www.gnu.org/licenses/>. 

*/

#include <stdarg.h>

#include <config.h>
#include <libcpak.h>


/* TODO: gettextize libcpak messages. */


/* Error messages for cpak_engine.error. */


const char *cpak_error_messages[] =
  {
    "Success",			/* 0: cpak_verify_ok. */
    "Unspecified fault",        /* 1: cpak_verify_fault. (generic) */
    "Invalid Argument"
  };

/* Log symbols */

const char* cpak_symbols[] = 
  {
    "Log: ",
    "System: ",
    "Verify :",
    "Assert :",
    "Check: "
  };

/* Program Log (prepend program name)*/

int cpak_log (const char *format, ...)
{
  va_list ap;
  int n;
  va_start (ap, format);
  n = fprintf (cpak_engine.log_stream, "%s", cpak_engine.symbol_log);
  n = vfprintf (cpak_engine.log_stream, format, ap);
  return n;
}


